title: Model Predictive Control Made Easy
description: ""
baseurl: ""
url: https://meco-group.github.io/impact-2025

theme: jekyll-nagymaros

copyright: MECO Research Team
indexing: true

exclude:
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-figure

sass:
  sourcemap: never
