name: mecoverse-robotics
channels:
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - scipy
  - pinocchio
  - pip
  - pip:
    - matplotlib==3.7.3
    - ipython
    - jupyter
    - multipledispatch
    - git+https://gitlab.kuleuven.be/meco-software/impact.git@ros_generator
    - roboticstoolbox-python
    - qpsolvers[open_source_solvers]

